name: Code-Signing Composite Action
description: Composite action for code signing
author: DA Team <da.team@sherwin.com>

inputs:
  group_id:
    required: true
    default: '11'
    description: 'Defaults to "gg-app-ncipher-csg-p-da-team" id'
  signing_profile_id: 
    required: true
    default: '4'
    description: 'Defaults to "JarSigning" profile id'
  artifact_path:
    required: true
    default: '${{ github.workspace }}'
    description: 'Path to the artifact that needs to be signed'
  artifact_name:
    required: true
    description: 'Name of the artifact to be signed'
  csg_username:
    required: true
    default: 'sa-digitalit-dss'
    description: 'Username for the CSG'
  csg_password:
    required: true
    description: 'Password for CSG'
  ghes_pat:
    required: true
    description: 'GHES Personal Access Token to Download CSG CLI from GitHub Release'
  csg_output_dir:
    required: false
    description: 'Signed file Name. Default is Security_<Artifact_Name>'
  
runs:
  using: "composite"  
  steps:
    - name: API call to download csg cli
      uses: sherwin-williams-co/sw-release-downloader-action@main
      with:
       repository: "Corp-IS-InfoSec/csg-cli"
       tag: v1.0.1
       fileName: "csg-cli-linux-amd64-v1.0.1.tar.gz"
       token: ${{ inputs.ghes_pat }}
       
    - name: Extract tar file
      run: |
         tar -xvf csg-cli-linux-amd64-v1.0.1.tar.gz
         mv ${{ github.workspace }}/output/linux/csg ${{ github.workspace }}/
         rm -rf ${{ github.workspace }}/output
      shell: bash
    
    - name: Sign artifact
      run: |
         filenameName = "Signed_${{ inputs.artifact_name }}"
         if [ -z "${{ inputs.csg_output_filename }}" ] 
         then
           echo "csg_output_filename is empty. Setting default Name"
           filenameName = "Signed_${{ inputs.artifact_name }}"
         else 
           echo "In else"
           filenameName = ${{ inputs.csg_output_filename }}
         fi
         echo "FileName $filenameName"
         export CSG_ADDR=https://csg.sherwin.com 
         ./csg sign -f ${{ inputs.artifact_path }}/${{ inputs.artifact_name }} -o $filenameName -g ${{ inputs.group_id }} -i ${{ inputs.signing_profile_id }} -u ${{ inputs.csg_username }} -p ${{ inputs.csg_password }}
      shell: bash
      
    - name: Clean Up the files
      run: |
         rm -rf ${{ github.workspace }}/csg-cli-linux-amd64-v1.0.1.tar.gz ${{ github.workspace }}/csg
      shell: bash
