name: Code-Signing Composite Action
description: Composite action for code signing
author: DA Team <da.team@sherwin.com>

inputs:
  group_id:
    required: true
    description: 'The group id'
  signing_profile_id: 
    required: true
    description: 'The signing profile id'
  artifact_path:
    required: true
    default: '${{ github.workspace }}'
    description: 'Path to the artifact that needs to be signed'
  artifact_name:
    required: true
    description: 'Name of the artifact to be signed'
  csg_username:
    required: true
    description: 'Username for the CSG'
  csg_password:
    required: true
    description: 'Password for CSG'
  csg_output_filename:
    required: false
    description: 'Signed file Name. Default is Signed_<Artifact_Name>'
  jf_artifactory_token:
    required: true
    description: 'Jfrog CLI JF Artifactory Token'
  
runs:
  using: "composite"  
  steps:
    - uses: jfrog/setup-jfrog-cli@v2.0.0
      env:
        JF_ARTIFACTORY_1: ${{ inputs.jf_artifactory_token }}

    - name: Download csg CLI from Artifactory
      run: |
        jfrog rt dl "third-party-installs/sherwin-williams-co/csg-cli/9/csg-cli-linux-amd64-v1.0.1.tar.gz" --flat --sort-by=created --sort-order=desc --limit=1
      shell: bash
      
    - name: Extract tar file
      run: |
         tar -xvf csg-cli-linux-amd64-v1.0.1.tar.gz
         mv ${{ github.workspace }}/output/linux/csg ${{ github.workspace }}/
         rm -rf ${{ github.workspace }}/output
      shell: bash
      
    - name: Check signing profiles
      run: |
        export CSG_ADDR=https://csg.sherwin.com 
        ./csg profiles -u ${{ inputs.csg_username }} -p ${{ inputs.csg_password }}
      bash: shell
    
    - name: Sign artifact
      run: |
         set -x
         fileName="${{ inputs.csg_output_filename }}"
         if [ -z "${{ inputs.csg_output_filename }}" ]
         then
           fileName="Signed_${{ inputs.artifact_name }}"
         fi
         export CSG_ADDR=https://csg.sherwin.com 
         ./csg sign -f ${{ inputs.artifact_path }}/${{ inputs.artifact_name }} -o $fileName -g ${{ inputs.group_id }} -i ${{ inputs.signing_profile_id }} -u ${{ inputs.csg_username }} -p ${{ inputs.csg_password }}
      shell: bash
      
    - name: Clean Up the files
      run: |
         rm -rf ${{ github.workspace }}/csg-cli-linux-amd64-v1.0.1.tar.gz ${{ github.workspace }}/csg
      shell: bash
