name: Test Code-Signing 
on: workflow_dispatch

jobs:
  code-sign:
    runs-on: sw-ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: API call to download csg cli
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "https://github.sherwin.com/Corp-IS-InfoSec/csg-cli"
        version: "tags/v1.0.1"
        file: "csg-cli-linux-amd64-v1.0.1.tar.gz"
        target: "subdir/csg-cli-linux-amd64-v1.0.1.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
      
#     - name: export CSG Address
#       run: export CSG_ADDR=https://csg.sherwin.com
    
#     - name: Login using cli (csg profiles)
#       run: |
#         csg profiles -u ${{ secrets.CSG_USERNAME }} -p ${{ secrets.CSG_PASSWORD }}
    
#     - name: Sign jar file
#       run: |
#         csg sign -f <file_path> -g <group_id> -i <sign_id> -u 
