name: Test Code-Signing 
on: workflow_dispatch

jobs:
  code-sign:
    runs-on: sw-ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with: 
        distribution: 'adopt'
        java-version: 11
    
    - name: execute jar
      run: java -jar HelloWorld.jar
