name: Test Code-Signing 
on: 
  workflow_dispatch:
    inputs:
      group_id:
        required: true
        default: '11'
        description: 'Defaults to "gg-app-ncipher-csg-p-da-team" id'
      signing_profile_id: 
        required: true
        default: '4'
        description: 'Defaults to "JarSigning" profile id'
      
jobs:
  code-sign:
    runs-on: sw-ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: API call to download csg cli
      uses: sherwin-williams-co/sw-release-downloader-action@main
      with:
       repository: "Corp-IS-InfoSec/csg-cli"
       tag: v1.0.1
       fileName: "csg-cli-linux-amd64-v1.0.1.tar.gz"
       token: ${{ secrets.GHES_PAT }}
       
    - name: Extract tar file
      run: |
         tar -xvf csg-cli-linux-amd64-v1.0.1.tar.gz
    
    - name: Sign jar file
      run: |
        cd ${{github.workspace}}/output/linux
        export CSG_ADDR=https://csg.sherwin.com 
        ./csg sign -f ${{ github.workspace}}/HelloWorld.jar -g ${{ github.event.inputs.group_id }} -i ${{ github.event.inputs.signing_profile_id }} -u ${{ secrets.CSG_USERNAME }} -p ${{ secrets.CSG_PASSWORD }}
